FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json* ./

# 强制将 npm 源设为淘宝/国内最新镜像源
RUN npm config set registry https://registry.npmmirror.com
RUN npm install

# Mount source code via volume at runtime
CMD ["npm", "run", "dev"]